DROP DATABASE IF EXISTS qa WITH (FORCE);

CREATE DATABASE qa;

-- lsof -i tcp:5432


-- Drop tables

DROP TABLE IF EXISTS questions CASCADE;
DROP TABLE IF EXISTS answers CASCADE;
DROP TABLE IF EXISTS photos CASCADE;

-- Create tables

CREATE TABLE questions (
  question_id INT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  product_id INT NOT NULL,
  question_body TEXT NOT NULL,
  question_date BIGINT NOT NULL,
  asker_name VARCHAR(50) NOT NULL,
  asker_email VARCHAR(100) NOT NULL,
  reported BOOLEAN NOT NULL DEFAULT false,
  question_helpfulness int NOT NULL DEFAULT 0
);

CREATE TABLE answers (
  id INT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  question_id integer NOT NULL,
  body TEXT NOT NULL,
  "date" BIGINT NOT NULL,
  answerer_name VARCHAR(50) NOT NULL,
  answerer_email VARCHAR(100) NOT NULL,
  reported BOOLEAN NOT NULL DEFAULT false,
  helpfulness INT NOT NULL DEFAULT 0
);

CREATE TABLE photos (
  photo_id INT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  answer_id INT NOT NULL,
  url VARCHAR(300) NOT NULL
);

-- psql postgres
-- psql -d qa -f db/schema.sql
